// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1, arg2) {
  return window['go']['backend']['LoginService']['Authenticate'](arg1, arg2);
}
